#!/bin/bash
# workflow execution script for analysis PeukerDouglasAutomatic
# auto-generated by /home/gisolve/cybergis/taudem/cmdseqgen.py on 2016-10-13 12:35:05.420737 


# step: pitremove
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/pitremove  -z results/output/PeukerDouglasAutomatic.tif   -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticfel.tif  

# step: d8flowdir
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/d8flowdir  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticfel.tif  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticp.tif -sd8 /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticsd8.tif  

# step: PeukerDouglas
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/peukerdouglas -par 0.4 0.1 0.05  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticfel.tif  -ss /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticss.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8 -o /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/__hsinputdir/Outlet.shp  -wg /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticss.tif -p /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticssa.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticad8.tif  

# step: Dropanalysis
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/dropanalysis -par 5 500 10 0 -o /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/__hsinputdir/Outlet.shp  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticp.tif -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticfel.tif -ssa /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticssa.tif -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticad8.tif  -drp /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticdrp.txt  

# step: Threshold
mpirun -np 20 -f /var/spool/torque/aux//44114.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/threshold  -thresh /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticdrp.txt.tif -ssa /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticssa.tif  -src /gpfs/largeblockFS/scratch/gisolve/tmp/44114.cg-gpu01/taudem/PeukerDouglasAutomaticsrc.tif  
