#!/bin/bash
# workflow execution script for analysis CubRiverAnalysis
# auto-generated by /home/gisolve/cybergis/taudem/cmdseqgen.py on 2016-11-04 13:42:51.580208 


# step: pitremove
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/pitremove  -z results/output/CubRiverAnalysis.tif   -fel /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisfel.tif  

# step: d8flowdir
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/d8flowdir  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisfel.tif  -p /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisp.tif -sd8 /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysissd8.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8  -p /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisad8o.tif  

# step: threshold
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/threshold -thresh 1000  -ssa /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisad8o.tif  -src /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysissrc.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8  -p /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisad8.tif  

# step: Streamnet
mpirun -np 20 -f /var/spool/torque/aux//46204.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/streamnet  -p /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisp.tif -fel /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisfel.tif -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisad8.tif -src /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysissrc.tif  -w /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisw.tif -ord /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisord.tif -tree /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysistree.dat -net /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysisnet.shp -coord /gpfs/largeblockFS/scratch/gisolve/tmp/46204.cg-gpu01/taudem/CubRiverAnalysiscoord.dat  
