#!/bin/bash
# workflow execution script for analysis dem
# auto-generated by /home/gisolve/cybergis/taudem/cmdseqgen.py on 2016-10-15 10:32:20.010213 


# step: pitremove
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/pitremove  -z results/output/dem.tif   -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demfel.tif  

# step: d8flowdir
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/d8flowdir  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demfel.tif  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demp.tif -sd8 /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demsd8.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8 -o /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/__hsinputdir/Outlet.shp  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demad8o.tif  

# step: threshold
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/threshold -thresh 1000  -ssa /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demad8o.tif  -src /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demsrc.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demad8.tif  

# step: Streamnet
mpirun -np 20 -f /var/spool/torque/aux//44155.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/streamnet -o /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/__hsinputdir/Outlet.shp  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demp.tif -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demfel.tif -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demad8.tif -src /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demsrc.tif  -w /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demw.tif -ord /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demord.tif -tree /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demtree.dat -net /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demnet.shp -coord /gpfs/largeblockFS/scratch/gisolve/tmp/44155.cg-gpu01/taudem/demcoord.dat  
