#!/bin/bash
# workflow execution script for analysis dem
# auto-generated by /home/gisolve/cybergis/taudem/cmdseqgen.py on 2016-10-24 18:13:56.986896 


# step: pitremove
mpirun -np 20 -f /var/spool/torque/aux//44537.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/pitremove  -z results/output/dem.tif   -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demfel.tif  

# step: d8flowdir
mpirun -np 20 -f /var/spool/torque/aux//44537.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/d8flowdir  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demfel.tif  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demp.tif -sd8 /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demsd8.tif  

# step: aread8
mpirun -np 20 -f /var/spool/torque/aux//44537.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/aread8 -wg /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/__hsinputdir/Startrc.tif  -p /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demp.tif  -ad8 /gpfs/largeblockFS/scratch/gisolve/tmp/44537.cg-gpu01/taudem/demad8o.tif  
