#!/bin/bash
# workflow execution script for analysis dem2
# auto-generated by /home/gisolve/cybergis/taudem/cmdseqgen.py on 2016-10-24 18:45:32.638791 


# step: pitremove
mpirun -np 20 -f /var/spool/torque/aux//44540.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/pitremove  -z results/output/dem2.tif   -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2fel.tif  

# step: dinfflowdir
mpirun -np 20 -f /var/spool/torque/aux//44540.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/dinfflowdir  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2fel.tif  -ang /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2ang.tif -slp /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2slp.tif  

# step: DinfDistDown
mpirun -np 20 -f /var/spool/torque/aux//44540.cg-gpu01 /gpfs_scratch/taudem/TauDEM-5.3.5/dinfdistdown -src /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/__hsinputdir/demad8o.tif -m ave v  -fel /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2fel.tif -ang /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2ang.tif  -dd /gpfs/largeblockFS/scratch/gisolve/tmp/44540.cg-gpu01/taudem/dem2dd.tif  
